# Generated by Django 4.0.3 on 2024-05-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CodeList',
        ),
    ]
