# Generated by Django 4.0.3 on 2024-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_sidemenulist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideSubMenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Level', models.DecimalField(decimal_places=0, max_digits=5)),
                ('seq', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
