# Generated by Django 4.0.3 on 2024-05-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
